version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      types:
        patterns:
          - '@types/*'
      eslint:
        patterns:
          - 'eslint*'
          - '@typescript-eslint/*'
      vite:
        patterns:
          - 'vite*'
          - 'vitest*'

  - package-ecosystem: cargo
    directory: /src-tauri
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
